### ISSUE TITLE
all destroy requests failing

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1041]
Both self hosted and service vendor hosted destroy requests are failing with below error -

14:31:04.707 [http-nio-8080-exec-4] INFO  o.e.x.m.logging.CustomHttpLogWriter [af831bb7-6340-4589-b2b8-be1d6cfa056d]- Response: 202 Accepted Duration: 11ms  {"resultType":"Success","details":["Task for destroying managed service 7c106018-886d-4404-b648-3259d6eead07 has started."],"success":true}
14:31:04.708 [thread-pool-11] ERROR o.s.a.i.SimpleAsyncUncaughtExceptionHandler [7c106018-886d-4404-b648-3259d6eead07]- Unexpected exception occurred invoking async method: public void org.eclipse.xpanse.modules.deployment.DeployService.asyncDestroyService(org.eclipse.xpanse.modules.orchestrator.deployment.Deployment,org.eclipse.xpanse.modules.orchestrator.deployment.DeployTask)
org.springframework.security.access.AccessDeniedException: No permissions to view details of services belonging to other users.
	at org.eclipse.xpanse.modules.deployment.DeployService.getDeployServiceEntity(DeployService.java:722)
	at org.eclipse.xpanse.modules.deployment.DeployService.destroy(DeployService.java:318)
	at org.eclipse.xpanse.modules.deployment.DeployService.asyncDestroyService(DeployService.java:313)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:751)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at org.eclipse.xpanse.modules.deployment.async.ThreadMdcUtil$1.call(ThreadMdcUtil.java:38)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
14:31:04.811 [http-nio-8080-exec-6] DEBUG o.s.security.web

**Comment by swaroopar** [comment]
@WangLiNaruto can you please have a look at this when possible?

**Comment by WangLiNaruto** [comment]
@swaroopar sure
