### ISSUE TITLE
workflowApi - PUT requests return http 500 if ID is unknown 

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1179]
when manageFailedOrder and completeTask methods are called with an invalid order ID, the method returns HTTP 500.

We must return http 400 with a valid custom exception

05:31:56.648 [http-nio-8080-exec-7] ERROR o.e.x.a.e.h.CommonExceptionHandler [f85a03c6-1f67-43d0-8ba9-aa12d58d8a70]- handleRuntimeException: 
org.activiti.engine.ActivitiObjectNotFoundException: Cannot find task with id 12344
	at org.activiti.engine.impl.cmd.NeedsActiveTaskCmd.execute(NeedsActiveTaskCmd.java:53)
	at org.activiti.engine.impl.interceptor.CommandInvoker$1.run(CommandInvoker.java:41)
	at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:82)
	at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:61)
	at org.activiti.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:46)
	at org.activiti.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:52)
	at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:63)
	at org.activiti.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:51)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at org.activiti.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:49)
	at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:33)
	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:59)
	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:54)

**Comment by WangLiNaruto** [comment]
let me do it
