### ISSUE TITLE
migrate workflow - destroy failure step fails to create a user task

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1180]
when a destroy step fails, the job fails with below exception

05:31:28.014 [thread-pool-8] INFO  o.e.x.m.w.h.m.MigrateDestroyProcess [a13b99eb-92cd-487e-a45a-4c0e47c58f8d]- Process instance: 22544 retry destroy service : 087d5f9c-eace-45ce-90cc-d933062eb856,RetryNum:1
05:31:28.014 [thread-pool-8] INFO  o.e.x.m.w.h.m.MigrateDestroyProcess [a13b99eb-92cd-487e-a45a-4c0e47c58f8d]- Migration workflow start destroying old service with service id:087d5f9c-eace-45ce-90cc-d933062eb856
05:31:28.016 [thread-pool-8] ERROR o.e.x.m.w.h.m.MigrateDestroyProcess [a13b99eb-92cd-487e-a45a-4c0e47c58f8d]- Migration workflow destroy old service with id:087d5f9c-eace-45ce-90cc-d933062eb856 failed. error:org.eclipse.xpanse.modules.models.service.deploy.exceptions.PluginNotFoundException: Can't find suitable plugin and resource handler for the Task.
05:31:28.016 [thread-pool-8] INFO  o.e.x.m.w.h.m.MigrateDestroyProcess [a13b99eb-92cd-487e-a45a-4c0e47c58f8d]- Migration workflow completed destroying old service with id:087d5f9c-eace-45ce-90cc-d933062eb856, success:false
05:31:28.018 [thread-pool-8] ERROR o.a.e.i.interceptor.CommandContext [a13b99eb-92cd-487e-a45a-4c0e47c58f8d]- Error while closing command context
org.activiti.engine.ActivitiException: Unknown property used in expression: ${assignee}
	at org.activiti.engine.impl.el.JuelExpression.getValueFromContext(JuelExpression.java:97)
	at org.activiti.engine.impl.el.JuelExpression.getValue(JuelExpression.java:54)
	at org.activiti.engine.impl.bpmn.behavior.UserTaskActivityBehavior.handleAssignments(UserTaskActivityBehavior.java:290)
	at org.activiti.engine.impl.bpmn.behavior.UserTaskActivityBehavior.execute(UserTaskActivityBehavior.java:225)
	at org.activiti.engine.impl.agenda.ContinueProcessOperation.executeActivityBehavior(ContinueProcessOperation.java:230)
	at org.activiti.engine.impl.agenda.ContinueProcessOperation.executeSynchronous(ContinueProcessOperation.java:168)
	at org.activiti.engine.impl.agenda.ContinueProcessOperation.continueThroughFlowNode(ContinueProcessOperation.java:117)
	at org.activiti.engine.impl.agenda.ContinueProcessOperation.run(ContinueProcessOperation.java:82)
	at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:77)
	at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:61)
	at org.activiti.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:46)
	at org.activiti.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:52)
	at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:63)
	at org.activiti.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:51)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at org.activiti.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:49)
	at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:33)
	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:59)
	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:54)

**Comment by WangLiNaruto** [comment]
let me do it
