### ISSUE TITLE
error in addServicePolicy request audit

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1720]
We see the below error in logs

2024-06-18T09:19:48.9007712Z 20240618 09:19:48.796 [main] INFO  o.e.x.api.config.CspPluginValidator [ada2b80a-a05a-4c7f-abd3-f900f5aa6cc8] [01cdef9a-1095-44cd-be94-965f2f00b51c]- Validate request parameters for method: addServicePolicy
2024-06-18T09:19:48.9011215Z 20240618 09:19:48.797 [main] ERROR o.e.xpanse.api.config.AuditLogWriter [ada2b80a-a05a-4c7f-abd3-f900f5aa6cc8] [01cdef9a-1095-44cd-be94-965f2f00b51c]- Get csp with annotation @AuditApiRequest error.
2024-06-18T09:19:48.9013289Z java.lang.IllegalArgumentException: argument type mismatch
2024-06-18T09:19:48.9014678Z 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:107)
2024-06-18T09:19:48.9016077Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
2024-06-18T09:19:48.9017372Z 	at org.eclipse.xpanse.api.config.AuditLogWriter.getCspFromMethodInfo(AuditLogWriter.java:107)
2024-06-18T09:19:48.9018867Z 	at org.eclipse.xpanse.api.config.AuditLogWriter.getCsp(AuditLogWriter.java:90)
2024-06-18T09:19:48.9020588Z 	at org.eclipse.xpanse.api.config.AuditLogWriter.auditRequest(AuditLogWriter.java:65)
2024-06-18T09:19:48.9022707Z 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
2024-06-18T09:19:48.9024141Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
2024-06-18T09:19:48.9025759Z 	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:637)
2024-06-18T09:19:48.9027831Z 	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:627)
2024-06-18T09:19:48.9029548Z 	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:71)
2024-06-18T09:19:48.9031286Z 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
2024-06-18T09:19:48.9033117Z 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
2024-06-18T09:19:48.9035152Z 	at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:57)
2024-06-18T09:19:48.9037300Z 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
2024-06-18T09:19:48.9039169Z 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
2024-06-18T09:19:48.9041171Z 	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:58)
2024-06-18T09:19:48.9043247Z 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
2024-06-18T09:19:48.9045091Z 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
2024-06-18T09:19:48.9047593Z 	at org.springframework.security.authorization.method.AuthorizationManagerBeforeMethodInterceptor.proceed(AuthorizationManagerBeforeMethodInterceptor.java:269)
2024-06-18T09:19:48.9051240Z 	at org.springframework.security.authorization.method.AuthorizationManagerBeforeMethodInterceptor.attemptAuthorization(AuthorizationManagerBeforeMethodInterceptor.java:264)
2024-06-18T09:19:48.9054446Z 	at org.springframework.security.authorization.method.AuthorizationManagerBeforeMethodInterceptor.invoke(AuthorizationManagerBeforeMethodInterceptor.java:197)
2024-06-18T09:19:48.9056902Z 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
2024-06-18T09:19:48.9058758Z 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
2024-06-18T09:19:48.9060626Z 	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
2024-06-18T09:19:48.9062975Z 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
2024-06-18T09:19:48.9064830Z 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
2024-06-18T09:19:48.9066622Z 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
2024-06-18T09:19:48.9068472Z 	at org.eclipse.xpanse.api.controllers.ServicePolicyManageApi$$SpringCGLIB$$0.addServicePolicy(<generated>)
2024-06-18T09:19:48.9070252Z 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
2024-06-18T09:19:48.9071629Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)

**Comment by baixinsui** [comment]
I will fix it.
