### ISSUE TITLE
error when deployment fails with missing credentials

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#2150]
- [ ] When deployment fails due to missing credentials, there is an error processing terraform result. There is no need to process terraform result since there was nothing executed. 
- [ ] Service status is also set wrongly to 'rollback failed' due to this. 

20241125 19:35:08.570 [http-nio-8080-exec-7] INFO  o.e.x.m.logging.CustomHttpLogWriter [6b0cb5a0-ab2e-43c8-b1b6-a431e5dbf98a] [] []- Request: POST /xpanse/services  {"category":"compute","csp":"HuaweiCloud","flavor":"2vCPUs-8GB-normal","region":{"name":"cn-southwest-2","site":"Chinese Mainland","area":"Asia China"},"serviceName":"terraform-ecs","version":"1.0.0","customerServiceName":"dfdfdfd","serviceHostingType":"self","availabilityZones":{},"eulaAccepted":true,"billingMode":"Pay per Use","serviceRequestProperties":{}}
 Keploy: 2024-11-25T19:35:08+01:00    INFO     Keploy has captured test cases for the user's application.   {"path": "/opt/repos/forked/osc/runtime/src/test/resources/keploy/test-set-6/tests", "testcase name": "test-35"}
20241125 19:35:08.588 [http-nio-8080-exec-7] INFO  o.e.x.api.config.CspPluginValidator [6b0cb5a0-ab2e-43c8-b1b6-a431e5dbf98a] [] []- Validate request parameters for method: deploy
20241125 19:35:08.717 [http-nio-8080-exec-7] INFO  o.e.x.m.deployment.PolicyValidator [6b0cb5a0-ab2e-43c8-b1b6-a431e5dbf98a] [63b112eb-7bca-464d-81c1-21d8fe1b7904] [b82a03f6-2d9b-49b6-a74d-4621e6628cc1]- No service or user policies found.
20241125 19:35:08.723 [http-nio-8080-exec-7] INFO  o.e.x.m.d.u.DeploymentScriptsHelper [6b0cb5a0-ab2e-43c8-b1b6-a431e5dbf98a] [63b112eb-7bca-464d-81c1-21d8fe1b7904] [b82a03f6-2d9b-49b6-a74d-4621e6628cc1]- Created deployment script files successful
20241125 19:35:08.723 [http-nio-8080-exec-7] ERROR o.e.x.m.credential.CredentialCenter [6b0cb5a0-ab2e-43c8-b1b6-a431e5dbf98a] [63b112eb-7bca-464d-81c1-21d8fe1b7904] [b82a03f6-2d9b-49b6-a74d-4621e6628cc1]- Get credential from cache by key CredentialCacheKey[csp=HUAWEI_CLOUD, site=Chinese Mainland, credentialType=VARIABLES, credentialName=AK_SK, userId=no-auth-user-id] failed. error:No credential cache entry found with key: CredentialCacheKey[csp=HUAWEI_CLOUD, site=Chinese Mainland, credentialType=VARIABLES, credentialName=AK_SK, userId=no-auth-user-id]
20241125 19:35:08.726 [http-nio-8080-exec-7] INFO  o.e.x.m.d.DeployResultManager [6b0cb5a0-ab2e-43c8-b1b6-a431e5dbf98a] [63b112eb-7bca-464d-81c1-21d8fe1b7904] [b82a03f6-2d9b-49b6-a74d-4621e6628cc1]- Update deploy service entity 63b112eb-7bca-464d-81c1-21d8fe1b7904 with deploy result DeployResult(orderId=b82a03f6-2d9b-49b6-a74d-4621e6628cc1, isTaskSuccessful=false, message=Order task b82a03f6-2d9b-49b6-a74d-4621e6628cc1 to deploy the service 63b112eb-7bca-464d-81c1-21d8fe1b7904 failed. No credential information found for the given Csp:HuaweiCloud., resources=null, outputProperties={}, deploymentGeneratedFiles={}, deployerVersionUsed=null, tfStateContent=null)
20241125 19:35:08.729 [http-nio-8080-exec-7] ERROR o.e.x.m.d.DeployResultManager [6b0cb5a0-ab2e-43c8-b1b6-a431e5dbf98a] [63b112eb-7bca-464d-81c1-21d8fe1b7904] [b82a03f6-2d9b-49b6-a74d-4621e6628cc1]- Exception occurred in handling deployment result.
java.lang.IllegalArgumentException: argument "content" is null
        at com.fasterxml.jackson.databind.ObjectMapper._assertNotNull(ObjectMapper.java:5060)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3815)
        at org.eclipse.xpanse.plugins.huaweicloud.resourcehandler.HuaweiCloudTerraformResourceHandler.handler(HuaweiCloudTerraformResourceHandler.java:49)
        at org.eclipse.xpanse.modules.deployment.DeployResultManager.updateDeployServiceEntityWithDeployResult(DeployResultManager.java:195)
        at org.eclipse.xpanse.modules.deployment.DeployResultManager.updateServiceWithDeployResult(DeployResultManager.java:107)
        at org.eclipse.xpanse.modules.deployment.DeployService.deployService(DeployService.java:407)
        at org.eclipse.xpanse.modules.deployment.DeployService.createOrderToDeployNewService(DeployService.java:119)
        at org.eclipse.xpanse.api.controllers.ServiceDeployerApi.deploy(ServiceDeployerApi.java:192)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:355)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
        at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:58)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
        at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:57)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
        at org.eclipse.xpanse.api.config.AuditLogWriter.auditRequest(AuditLogWriter.java:67)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:637)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:627)
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:71)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
        at org.eclipse.xpanse.api.controllers.ServiceDeployerApi$$SpringCGLIB$$0.deploy(<generated>)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:255)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:188)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:926)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:831)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:195)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
        at org.zalando.logbook.servlet.LogbookFilter.doFilter(LogbookFilter.java:76)
        at org.zalando.logbook.servlet.HttpFilter.doFilter(HttpFilter.java:32)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
        at org.zalando.logbook.servlet.LogbookFilter.doFilter(LogbookFilter.java:76)
        at org.zalando.logbook.servlet.SecureLogbookFilter.doFilter(SecureLogbookFilter.java:32)
        at org.zalando.logbook.servlet.HttpFilter.doFilter(HttpFilter.java:32)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
        at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:113)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
        at org.eclipse.xpanse.modules.logging.LoggingWebFilter.doFilter(LoggingWebFilter.java:39)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:384)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
        at java.base/java.lang.Thread.run(Thread.java:1583)
20241125 19:35:08.748 [http-nio-8080-exec-7] INFO  o.e.x.m.d.DeployResultManager [6b0cb5a0-ab2e-43c8-b1b6-a431e5dbf98a] [63b112eb-7bca-464d-81c1-21d8fe1b7904] [a17a70b4-d6a1-4f68-9199-b50592c18c7c]- Performing rollback of already provisioned resources.
20241125 19:35:08.755 [http-nio-8080-exec-7] INFO  o.e.x.m.d.DeployResultManager [6b0cb5a0-ab2e-43c8-b1b6-a431e5dbf98a] [63b112eb-7bca-464d-81c1-21d8fe1b7904] [7dcb2779-0a42-48ad-95ee-8f6f8704bc96]- No resources need to destroy, the rollback task success.
20241125 19:35:08.759 [http-nio-8080-exec-7] INFO  o.e.x.m.d.DeployResultManager [6b0cb5a0-ab2e-43c8-b1b6-a431e5dbf98a] [63b112eb-7bca-464d-81c1-21d8fe1b7904] [7dcb2779-0a42-48ad-95ee-8f6f8704bc96]- Update deploy service entity 63b112eb-7bca-464d-81c1-21d8fe1b7904 with deploy result DeployResult(orderId=7dcb2779-0a42-48ad-95ee-8f6f8704bc96, isTaskSuccessful=true, message=null, resources=null, outputProperties={}, deploymentGeneratedFiles={}, deployerVersionUsed=null, tfStateContent=null)
20241125 19:35:08.760 [http-nio-8080-exec-7] ERROR o.e.x.m.d.DeployResultManager [6b0cb5a0-ab2e-43c8-b1b6-a431e5dbf98a] [63b112eb-7bca-464d-81c1-21d8fe1b7904] [7dcb2779-0a42-48ad-95ee-8f6f8704bc96]- Exception occurred in handling deployment result.
java.lang.IllegalArgumentException: argument "content" is null
        at com.fasterxml.jackson.databind.ObjectMapper._assertNotNull(ObjectMapper.java:5060)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3815)
        at org.eclipse.xpanse.plugins.huaweicloud.resourcehandler.HuaweiCloudTerraformResourceHandler.handler(HuaweiCloudTerraformResourceHandler.java:49)
        at org.eclipse.xpanse.modules.deployment.DeployResultManager.updateDeployServiceEntityWithDeployResult(DeployResultManager.java:195)
        at org.eclipse.xpanse.modules.deployment.DeployResultManager.updateServiceWithDeployResult(DeployResultManager.java:107)
        at org.eclipse.xpanse.modules.deployment.DeployResultManager.rollbackOnDeploymentFailure(DeployResultManager.java:156)
        at org.eclipse.xpanse.modules.deployment.DeployResultManager.updateServiceWithDeployResult(DeployResultManager.java:120)
        at org.eclipse.xpanse.modules.deployment.DeployService.deployService(DeployService.java:407)
        at org.eclipse.xpanse.modules.deployment.DeployService.createOrderToDeployNewService(DeployService.java:119)
        at org.eclipse.xpanse.api.controllers.ServiceDeployerApi.deploy(ServiceDeployerApi.java:192)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:355)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
        at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:58)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
        at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:57)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
        at org.eclipse.xpanse.api.config.AuditLogWriter.auditRequest(AuditLogWriter.java:67)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:637)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:627)
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:71)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
        at org.eclipse.xpanse.api.controllers.ServiceDeployerApi$$SpringCGLIB$$0.deploy(<generated>)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:255)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:188)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:926)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:831)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:195)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
        at org.zalando.logbook.servlet.LogbookFilter.doFilter(LogbookFilter.java:76)
        at org.zalando.logbook.servlet.HttpFilter.doFilter(HttpFilter.java:32)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
        at org.zalando.logbook.servlet.LogbookFilter.doFilter(LogbookFilter.java:76)
        at org.zalando.logbook.servlet.SecureLogbookFilter.doFilter(SecureLogbookFilter.java:32)
        at org.zalando.logbook.servlet.HttpFilter.doFilter(HttpFilter.java:32)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
        at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:113)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
        at org.eclipse.xpanse.modules.logging.LoggingWebFilter.doFilter(LoggingWebFilter.java:39)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:384)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
        at java.base/java.lang.Thread.run(Thread.java:1583)
20241125 19:35:08.798 [http-nio-8080-exec-7] INFO  o.e.x.m.logging.CustomHttpLogWriter [6b0cb5a0-ab2e-43c8-b1b6-a431e5dbf98a] [63b112eb-7bca-464d-81c1-21d8fe1b7904] [7dcb2779-0a42-48ad-95ee-8f6f8704bc96]- Response: 400 Bad Request Duration: 227ms  {"resultType":"Credentials Not Found","details":["No credential information found for the given Csp:HuaweiCloud."],"success":false,"serviceId":"63b112eb-7bca-464d-81c1-21d8fe1b7904","orderId":"7dcb2779-0a42-48ad-95ee-8f6f8704bc96"}

**Comment by baixinsui** [comment]
I will fix it
