### ISSUE TITLE
App crashes with openapi file generation for credentialsApi fails

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#602]
If there are issues in generating the openapi file, then the application is fully crashing. 
We must log this error and still continue with the application startup.

14:49:55.745 [main] INFO  o.e.x.common.openapi.OpenApiUtil []- Download openapi client:D:\Users\s00828547\IdeaProjects\forked_clean\osc\openapi\openapi-generator-cli.jar from URL:https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/6.5.0/openapi-generator-cli-6.5.0.jar start.
14:50:17.326 [main] ERROR o.e.x.m.c.CredentialOpenApiGenerator []- credentialApi html file:flexibleEngine_variables_credentialApi.html creation failed.
java.net.ConnectException: Connection timed out: connect
14:50:17.379 [main] ERROR o.s.boot.SpringApplication []- Application run failed
java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:765)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:752)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:319)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
	at org.eclipse.xpanse.runtime.XpanseApplication.main(XpanseApplication.java:30)
Caused by: org.eclipse.xpanse.modules.models.common.exceptions.OpenApiFileGenerationException: credentialApi html file creation failed: Connection timed out: connect
	at org.eclipse.xpanse.modules.credential.CredentialOpenApiGenerator.createCredentialApi(CredentialOpenApiGenerator.java:161)
	at org.eclipse.xpanse.modules.credential.CredentialOpenApiGenerator.lambda$run$1(CredentialOpenApiGenerator.java:97)
	at java.base/java.util.HashMap$KeySet.forEach(HashMap.java:1008)
	at org.eclipse.xpanse.modules.credential.CredentialOpenApiGenerator.run(CredentialOpenApiGenerator.java:94)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:762)
	... 5 common frames omitted

**Comment by baixinsui** [comment]
I will take it.
