### ISSUE TITLE
HealthCheck API fails with null pointer when not all scopes selected

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#684]
HealthCheck API fails with null pointer when user logs in with only "openid" scope. No other services fails. 
If this service really needs the  other scopes, then we need a better exception to be thrown. 

07:06:42.792 [http-nio-8080-exec-3] ERROR o.e.x.a.e.CommonExceptionHandler [79f87688-2ce4-4847-b3c3-42853f8f2f31]- handleRuntimeException: 
java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "java.util.Map.get(Object)" is null
	at org.eclipse.xpanse.modules.security.zitadel.common.ZitadelUserAuthenticationConverter.getCurrentUserInfo(ZitadelUserAuthenticationConverter.java:36)
	at org.eclipse.xpanse.api.AdminServicesApi.processShownFields(AdminServicesApi.java:136)
	at org.eclipse.xpanse.api.AdminServicesApi.checkHealthOfBackendSystem(AdminServicesApi.java:85)
	at org.eclipse.xpanse.api.AdminServicesApi.healthCheck(AdminServicesApi.java:72)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:756)
	at org.springframework.security.authorization.method.AuthorizationManagerBeforeMethodInterceptor.invoke(AuthorizationManagerBeforeMethodInterceptor.java:199)

**Comment by jinyangyang222** [comment]
I will do this.
